# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:12
from __future__ import unicode_literals

import apps.accounts.mixins
import apps.accounts.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, validators=[apps.accounts.models.validateLengthGreaterThanTwo])),
                ('name', models.CharField(max_length=100, validators=[apps.accounts.models.validateLengthGreaterThanTwo])),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255, validators=[apps.accounts.models.validateLengthGreaterThanTwo])),
                ('dob', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
            bases=(apps.accounts.mixins.CustomMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
            },
        ),
    ]
